version: '3.7'

services:
  makepdfs:
    container_name: makepdfs
    build:
      context: .
      dockerfile: Dockerfile
    image: "docker.pkg.github.com/ksnifte/actions-makepdfs/makepdfs:${TAG:-latest}"
